### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by cybersecurity99** [Center-Sun/suricata-kafka-output#2]
11/4/2022 -- 12:44:36 - <Error> - brokers parameter required!
thread '<unnamed>' panicked at 'explicit panic', src/lib.rs:55:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)

**Comment by Center-Sun** [comment]
Hi, did you add kafka section to your suricata.yaml? seen  plugin can't find some necessary parameters.

**Comment by cybersecurity99** [comment]
Hi @Center-Sun , added this at end of file , exact copy paste in suricata.yaml



```
kafka:
  brokers: "kafka1:9092,kafka2:9092"
  topic: suricata
  client-id: suricata_client_01
  buffer-size: 1024
```


 I replaced kafka:port with my own server details. plugin is detected by suricata but it can't read parameters . Request you to try a demo of it in a Virtual Box maybe some things changed with 6.0.4

**Comment by Center-Sun** [comment]
Hi @cybersecurity99 ,  It's worked in my suricata-6.0.4.
I noticed you added the kafka section at the end of suricata.yaml ,the things you need to know,this project is a `eve output plugin`,so you should edit the eve-log section in suricata.yaml like this:
```
  # Extensible Event Format (nicknamed EVE) event log in JSON format
  - eve-log:
      enabled: yes
      filetype: kafka #regular|syslog|unix_dgram|unix_stream|redis|kafka
      filename: eve.json

      kafka:
        brokers: "kafka1:9092,kafka2:9092"
        topic: suricata
        client-id: suricata_client_01
        buffer-size: 1024

```

Hope it can helps you
